font_family JetBrainsMono Nerd Font
font_size 12.0

background_opacity 0.74
dynamic_background_opacity yes

confirm_os_window_close 0
enable_audio_bell no

window_padding_width 12

background #101512
foreground #d8e2d0

selection_background #5E8B4A
selection_foreground #101512

cursor #7AA16B
cursor_text_color #101512

active_border_color #5E8B4A
inactive_border_color #2E4A36

color0 #101512
color1 #c46a6a
color2 #5E8B4A
color3 #d6b36a
color4 #7AA16B
color5 #8a9b77
color6 #6d9b7a
color7 #d8e2d0

color8 #2E4A36
color9 #d17a7a
color10 #7AA16B
color11 #e0c17a
color12 #8fbf7f
color13 #a6b88f
color14 #83b890
color15 #e6eedf

# Pywal colors
include /home/nick/.cache/wal/kitty.conf
